[tools]
"cargo:stylua" = "2.4.1"
"cargo:tree-sitter-cli" = "0.26.8"
"github:hadolint/hadolint" = "2.14.0"
"github:jesseduffield/lazydocker" = "0.25.2"
"github:jesseduffield/lazygit" = "0.61.1"
lua = "5.1"
node = "24"
"npm:eslint" = "10.2.1"
"npm:prettier" = "3.8.3"
"npm:stylelint" = "17.9.0"
"npm:stylelint-config-standard" = "40.0.0"
"npm:stylelint-config-standard-scss" = "17.0.0"
"pipx:yamllint" = "1.38.0"
python = "3.14.4"
rust = "1.95"
uv = "0.11.7"

[settings]
lockfile = true

[settings.pipx]
uvx = true
