---
gui:
  scrollHeight: 3
  filterMode: fuzzy
  theme:
    optionsTextColor:
      - cyan
git:
  commit:
    signOff: true
update:
  days: 1
customCommands:
  - key: "<f9>"
    command: "git push --force-with-lease"
    context: "global"
    loadingText: "Force push (with lease)"
    description: "Force push (with lease)"
  - key: "<c-u>"
    command: "git merge --no-edit $(git rev-parse --abbrev-ref origin/HEAD)"
    context: "global"
    description: "Merge remote default branch"
    prompts:
      - type: "confirm"
        title: "Merge remote defalt branch"
        body: "Are you sure you want to merge origin/HEAD into {{ .SelectedLocalBranch.Name }}?"
  - key: "u"
    command: "git reset --soft HEAD~1"
    context: "commits"
    description: "Undo last commit"
    prompts:
      - type: "confirm"
        title: "Undo commit"
        body: "Are you sure you want to undo commit {{ slice .SelectedLocalBranch.CommitHash 0 8 }} - {{ .SelectedLocalBranch.Subject }}?"
  - key: "P"
    command: "git push {{.SelectedRemote.Name}} {{.SelectedLocalCommit.Sha}}:{{.SelectedLocalBranch.Name}}"
    context: "commits"
    loadingText: "Pushing commit {{ slice .SelectedLocalCommit.Sha 0 8 }} - {{ .SelectedLocalCommit.Name }}"
    description: "Push selected commit (and any preceding)"
    stream: yes
  - key: "<c-space>"
    context: "stash"
    prompts:
      - type: "input"
        title: "Patch file name without extension"
        key: "PatchFileName"
    command: 'git stash show "stash@{ {{ .SelectedStashEntry.Index }} }" -p > {{ .Form.PatchFileName }}.patch'
    description: "Create a patch file from selected stash"
  - key: "<c-space>"
    context: "commits"
    prompts:
      - type: "input"
        title: "Patch file name without extension"
        key: "PatchFileName"
    command: "git format-patch -1 {{ .SelectedLocalCommit.Sha }} --stdout > {{ .Form.PatchFileName }}.patch"
    description: "Create a patch file from selected commit"
  - key: "<c-space>"
    context: "files"
    prompts:
      - type: "input"
        title: "Patch file name without extension"
        key: "PatchFileName"
    command: "git diff --cached > {{ .Form.PatchFileName }}.patch"
    description: "Create a patch file from staged files"
  - key: "<c-space>"
    context: "localBranches"
    prompts:
      - type: "input"
        title: "Branch to create patch from"
        key: "BranchName"
        suggestions:
          preset: "branches"
      - type: "input"
        title: "Patch file name without extension"
        key: "PatchFileName"
    command: "git diff --merge-base {{ .Form.BranchName }} $(git rev-parse --abbrev-ref origin/HEAD) > {{ .Form.PatchFileName }}.patch"
    description: "Create a patch file from selected commit"
  - key: "<c-a>"
    context: "files"
    prompts:
      - type: "confirm"
        title: "Apply patch file"
        body: "Are you sure you want to apply {{ .SelectedFile.Name }}?"
    command: "git apply {{ .SelectedFile.Name }}"
    description: "Apply selected patch file"
