[tools]
"cargo:stylua" = "2.4.1"
"cargo:tree-sitter-cli" = "0.26.8"
"github:BurntSushi/ripgrep" = "15.1.0"
"github:hadolint/hadolint" = "2.14.0"
"github:jesseduffield/lazydocker" = "0.25.2"
"github:jesseduffield/lazygit" = "0.61.1"
lua = "5.1"
neovim = "0.12.2"
node = "24"
"npm:@github/copilot" = "1.0.36"
"npm:oxfmt" = "0.47.0"
"npm:oxlint" = "1.62.0"
"npm:stylelint" = "17.9.0"
"npm:stylelint-config-standard" = "40.0.0"
"npm:stylelint-config-standard-scss" = "17.0.0"
"pipx:harlequin" = "2.5.2"
"pipx:yamllint" = "1.38.0"
python = "3.14.4"
rust = "1.95"
uv = "0.11.7"

[settings]
lockfile = true

[settings.pipx]
uvx = true

[env]
